export const ADVERTISEMENTS_LOADING = 'ADVERTISEMENTS_LOADING';
export const ADVERTISEMENTS_FAILED = 'ADVERTISEMENTS_FAILED';
export const ADD_ADVERTISEMENT = 'ADD_ADVERTISEMENT';
export const ADD_ADVERTISEMENTS = 'ADD_ADVERTISEMENTS';
export const UPDATE_ADVERTISEMENTS = 'UPDATE_ADVERTISEMENTS';
